### ISSUE TITLE
Tests failing on 1.1

### ISSUE THREAD

**Issue by KristofferC** [antimon2/QDates.jl#4]
Hello, we are running tests against all registered packages in preparation of the 1.1 release (https://github.com/JuliaLang/julia/issues/30374). We noticed that your package started failing on 1.1 (but was working on 1.0.x). The reason for the failure is this line https://github.com/antimon2/QDates.jl/blob/dd74ea2c5dbe24dee6bb1c3a854c02e987ddde53/test/ranges.jl#L51 explicitly tests the state of the step range (which has been changed on 1.1). Relying on the exact form of the state for iterators is not advisable and one should try to use the iterator interface instead.

The package seems to still work fine, it is just the tests that are a bit too explicit.

**Comment by antimon2** [comment]
Thank you for your report.
I understand the circumstances.
I will fix (or invalidate) the test in the near future.

**Comment by antimon2** [comment]
@KristofferC
I released [QDates.jl v0.2.0](https://github.com/antimon2/QDates.jl/releases/tag/v0.2.0).
There are some fixes including this issue.
